wireguard: check name length
Signed-off-by: Fabian Bläse <fabian@blaese.de>

diff --git a/src/packages/fff/fff-gateway/files/etc/gateway.d/50-wireguard b/src/packages/fff/fff-gateway/files/etc/gateway.d/50-wireguard
--- a/src/packages/fff/fff-gateway/files/etc/gateway.d/50-wireguard
+++ b/src/packages/fff/fff-gateway/files/etc/gateway.d/50-wireguard
@@ -10,6 +10,12 @@ configure() {
 			return
 		fi
 
+		# ensure name length
+		if [ ${#name} -gt 15 ]; then
+			echo "ERROR: name $name is too long!"
+			exit 1
+		fi
+
 		# get rxcost
 		if rxcost=$(uci -q get gateway.$name.rxcost); then
 			rxcost="$rxcost"
