Consistent gateway.d indentation

diff --git a/src/packages/fff/fff-gateway/files/usr/sbin/configuregateway b/src/packages/fff/fff-gateway/files/usr/sbin/configuregateway
--- a/src/packages/fff/fff-gateway/files/usr/sbin/configuregateway
+++ b/src/packages/fff/fff-gateway/files/usr/sbin/configuregateway
@@ -6,7 +6,7 @@
 
 # This program is distributed in the hope that it will be useful,
 # but WITHOUT ANY WARRANTY; without even the implied warranty of
-# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.	See the
 # GNU General Public License for more details.
 
 
@@ -27,96 +27,96 @@ BOARD="$(uci get board.model.name)"
 
 
 execute_subshell() {
-    if [ $# -ne 1 ]; then
-        echo "Usage:" "$0" "<function>"
-    fi
+	if [ $# -ne 1 ]; then
+		echo "Usage:" "$0" "<function>"
+	fi
 
-    for script in /etc/gateway.d/*; do
-        (
-            # unset function to prevent executing parents shell function
-            unset -f "$1"
-            . "$script"
+	for script in /etc/gateway.d/*; do
+		(
+			# unset function to prevent executing parents shell function
+			unset -f "$1"
+			. "$script"
 
-            if type "$1" | grep "shell function" > /dev/null; then
-                "$1"
-            fi
-        )
+			if type "$1" | grep "shell function" > /dev/null; then
+				"$1"
+			fi
+		)
 
-        if [ $? -ne 0 ]; then
-            echo "Error when executing" "$1" "from" "$(basename "$script")"
-            exit 1
-        fi
-    done
+		if [ $? -ne 0 ]; then
+			echo "Error when executing" "$1" "from" "$(basename "$script")"
+			exit 1
+		fi
+	done
 }
 
 configure() {
-    # ensure client config exists
-    if ! uci get gateway.@client[0] > /dev/null; then
-        echo "ERROR: No client config or error parsing config!"
-        exit 1
-    fi
+	# ensure client config exists
+	if ! uci get gateway.@client[0] > /dev/null; then
+		echo "ERROR: No client config or error parsing config!"
+		exit 1
+	fi
 
 
-    echo "This script might remove existing vlans, interfaces, addresses, etc."
-    read -r -p "Do you really want to continue? (y/n) " response
-    if ! [ "$response" == "y" ] || [ "$response" == "Y" ]; then
-        exit 1
-    fi
+	echo "This script might remove existing vlans, interfaces, addresses, etc."
+	read -r -p "Do you really want to continue? (y/n) " response
+	if ! [ "$response" == "y" ] || [ "$response" == "Y" ]; then
+		exit 1
+	fi
 
 
-    execute_subshell configure
+	execute_subshell configure
 
-    exit 0
+	exit 0
 }
 
 restart_services() {
-    execute_subshell reload
-    reload_config
+	execute_subshell reload
+	reload_config
 }
 
 apply_changes() {
-    execute_subshell apply
-    restart_services
-    exit 0
+	execute_subshell apply
+	restart_services
+	exit 0
 }
 
 revert_changes() {
-    execute_subshell revert
-    exit 0
+	execute_subshell revert
+	exit 0
 }
 
 test_changes() {
-    restart_services
+	restart_services
 
-    sleep 5
-    echo "services restarted. waiting up to 200s for SIGINT.."
-    sleep 200
-    echo "reverting changes.."
+	sleep 5
+	echo "services restarted. waiting up to 200s for SIGINT.."
+	sleep 200
+	echo "reverting changes.."
 
-    revert_changes
-    restart_services
+	revert_changes
+	restart_services
 }
 
 
 usage() {
-    echo Usage: $0 [OPTION];
-    echo;
-    echo "Options:"
-    echo "  -c: configure. No commit, no restart!"
-    echo "  -t: test changes. Restarts services, waits up to 200s for SIGINT"
-    echo "  -a: apply changes"
-    echo "  -r: revert changes"
+	echo Usage: $0 [OPTION];
+	echo;
+	echo "Options:"
+	echo "	-c: configure. No commit, no restart!"
+	echo "	-t: test changes. Restarts services, waits up to 200s for SIGINT"
+	echo "	-a: apply changes"
+	echo "	-r: revert changes"
 }
 
 
 if [ $# != 1 ]; then
-    usage; exit 1
+	usage; exit 1
 fi
 
 case "$1" in
-    -c) configure ;;
-    -t) test_changes ;;
-    -a) apply_changes ;;
-    -r) revert_changes ;;
-    *) usage; exit 1 ;;
+	-c) configure ;;
+	-t) test_changes ;;
+	-a) apply_changes ;;
+	-r) revert_changes ;;
+	*) usage; exit 1 ;;
 esac
